environment: "production"

noindex: true

disqus:

google_analytics:

url: "https://gabrieljones.it"

baseurl: "/"

permalink: /:title/

version: v4.0.0

sass:
  style: :compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - AUTHORS
  - LICENSE
  - README.md
  - CNAME

file_css: "https://www.comune.bologna.it/style.min.css?v=1625"
head: 


title: "Sito di esempio"
description: "sito di esempio"
keywords: "esempio"
author: "Mario Rossi"
language: "it"
og_image: "/assets/logo.png"
canonical_url: "https://blog.gabrieljones.it/gabrieljones/"
rss_feed_url: "https://blog.gabrieljones.it/gabrieljones/feed"
